"""
Category Service - DynamoDB implementation using PynamoDB.
Preserves original method signatures and integrates with audit/notification services.
"""
from datetime import datetime
from typing import List, Optional, Dict, Any
import logging

# DynamoDB models
from ..models.Categories import Category, validate_category_id
from ..models.Product import Product, validate_product_id
from .product_service import ProductService

# Other services
from .audit_service import AuditLogService
from notifications.services import notification_service
from app.utils import generate_sk

logger = logging.getLogger(__name__)


class CategoryService:
    """
    Complete DynamoDB-based Category Service.
    Exact replica of original MongoDB service method signatures.
    """

    VALID_CATEGORY_PREFIXES = ('CAT-',)
    UNCATEGORIZED_ID_CANDIDATES = ['CAT-0001']   # Fixed ID for Uncategorized
    DEFAULT_SUBCATEGORY_NAME = 'General'         # Kept for compatibility

    def __init__(self):
        """Initialize with DynamoDB models and auxiliary services."""
        self.audit_service = AuditLogService()
        self.product_service = ProductService()
        self._ensure_tables_exist()
        self.ensure_uncategorized_category_exists()

    # -----------------------------------------------------------------
    # TABLE INITIALIZATION (replaces MongoDB index creation)
    # -----------------------------------------------------------------
    def _ensure_tables_exist(self):
        """Ensure DynamoDB tables exist (called at startup)."""
        try:
            if not Category.exists():
                Category.create_table(wait=True)
                logger.info("Category table created")
            if not Product.exists():
                Product.create_table(wait=True)
                logger.info("Product table created")
        except Exception as e:
            logger.error(f"Error ensuring tables: {e}")

    # -----------------------------------------------------------------
    # UTILITY METHODS (preserved signatures)
    # -----------------------------------------------------------------
    def _is_valid_category_id(self, category_id):
        """Check if category ID format is valid (CAT-####)."""
        return validate_category_id(category_id)

    def _ensure_subcategory_present(self, category_id, category_doc, subcategory_name):
        """
        Legacy method – ensures a subcategory exists.
        category_doc is kept for signature compatibility but not used.
        """
        category = Category.get_by_id(category_id)
        if not category:
            return
        if not any(sc.name == subcategory_name for sc in category.sub_categories):
            category.add_subcategory(
                name=subcategory_name,
                description=f'Default {subcategory_name} subcategory'
            )

    def generate_category_id(self):
        """
        Generate next CAT-#### ID.
        In DynamoDB, IDs are generated by the model; this method is kept for compatibility.
        """
        return generate_sk('CAT-', 'category_seq')

    def generate_subcategory_id(self):
        """Generate next SUB-##### ID."""
        return generate_sk('SUB-', 'subcategory_seq')

    def _send_category_notification(self, action_type, category_name, category_id=None, additional_metadata=None):
        """Send notification for category actions."""
        templates = {
            'created':          {'title': 'Category Created',          'priority': 'medium'},
            'updated':          {'title': 'Category Updated',         'priority': 'medium'},
            'soft_deleted':     {'title': 'Category Deleted',         'priority': 'medium'},
            'hard_deleted':     {'title': 'Category Permanently Deleted', 'priority': 'high'},
            'restored':         {'title': 'Category Restored',        'priority': 'medium'},
            'bulk_deleted':     {'title': 'Categories Bulk Deleted',  'priority': 'low'},
            'bulk_updated':     {'title': 'Categories Bulk Updated',  'priority': 'low'},
            'subcategory_added':   {'title': 'Subcategory Added',     'priority': 'low'},
            'subcategory_removed': {'title': 'Subcategory Removed',   'priority': 'low'},
            'products_moved':   {'title': 'Products Moved',           'priority': 'low'},
        }
        tpl = templates.get(action_type)
        if not tpl:
            return
        metadata = {
            "category_id": str(category_id) if category_id else "",
            "category_name": category_name,
            "action_type": f"category_{action_type}",
            **(additional_metadata or {})
        }
        notification_service.create_notification(
            title=tpl['title'],
            message=f"{tpl['title']}: {category_name}" if category_name else tpl['title'],
            priority=tpl['priority'],
            notification_type="system",
            metadata=metadata,
            action_type=f"category_{action_type}"
        )

    # -----------------------------------------------------------------
    # CORE CATEGORY OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def create_category(self, category_data, current_user=None):
        """Create a new category."""
        try:
            category_name = self._validate_category_data(category_data)
            logger.info(f"Creating category: {category_name}")

            # Use model to create category
            category = Category.create_category(
                category_name=category_name,
                description=category_data.get("description"),
                icon=category_data.get("icon"),
                sort_order=category_data.get("sort_order", 0)
            )

            # Add image fields if present (for compatibility)
            image_fields = ['image_url', 'image_filename', 'image_size', 'image_type', 'image_uploaded_at']
            for field in image_fields:
                if field in category_data and category_data[field] is not None:
                    setattr(category, field, category_data[field])
            category.save()

            # Prepare subcategories (the model may have created default ones)
            # If the input includes custom subcategories, add them
            if 'sub_categories' in category_data:
                for sub in category_data['sub_categories']:
                    category.add_subcategory(
                        name=sub['name'],
                        description=sub.get('description', ''),
                        icon=sub.get('icon'),
                        sort_order=sub.get('sort_order', 0),
                        status=sub.get('status', 'active')
                    )

            # Send notification
            self._send_category_notification(
                'created',
                category.category_name,
                category.sk,
                {'created_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='create',
                    user=current_user,
                    category=category,
                    details={'category_data': category_data}
                )

            logger.info(f"Category '{category_name}' created with ID {category.sk}")
            return self._enrich_category(category)

        except Exception as e:
            logger.error(f"Error creating category: {e}", exc_info=True)
            raise Exception(f"Error creating category: {str(e)}")

    def get_all_categories(self, include_deleted=False, limit=None, skip=None):
        """Get all categories with product counts."""
        try:
            categories = Category.get_all_categories(include_deleted=include_deleted)
            if skip:
                categories = categories[skip:]
            if limit:
                categories = categories[:limit]

            # Enrich with product counts
            result = [self._enrich_category(cat) for cat in categories]
            return result
        except Exception as e:
            logger.error(f"Error getting categories: {e}")
            raise Exception(f"Error getting categories: {str(e)}")

    def get_category_by_id(self, category_id, include_deleted=False):
        """Get category by ID with product counts."""
        try:
            if not self._is_valid_category_id(category_id):
                return None

            category = Category.get_by_id(category_id)
            if not category:
                return None
            if not include_deleted and category.isDeleted:
                return None

            return self._enrich_category(category)
        except Exception as e:
            logger.error(f"Error getting category by ID {category_id}: {e}")
            raise Exception(f"Error getting category: {str(e)}")

    def update_category(self, category_id, category_data, current_user=None):
        """Update category."""
        try:
            logger.info(f"Updating category {category_id}")
            if not self._is_valid_category_id(category_id):
                return None

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return None

            old_values = category.to_dict()

            # Validate category name if being updated
            if 'category_name' in category_data:
                new_name = category_data['category_name'].strip()
                if new_name != category.category_name:
                    existing = Category.get_by_name(new_name)
                    if existing and existing.sk != category.sk:
                        raise ValueError(f"Category name '{new_name}' already exists")

            # Update allowed fields
            allowed_fields = {'category_name', 'description', 'status', 'sort_order', 'icon'}
            updates = {k: v for k, v in category_data.items() if k in allowed_fields}
            category.update_category(**updates)

            # Update image fields if present
            image_fields = ['image_url', 'image_filename', 'image_size', 'image_type', 'image_uploaded_at']
            for field in image_fields:
                if field in category_data:
                    setattr(category, field, category_data[field])
            category.save()

            # Send notification
            self._send_category_notification(
                'updated',
                category.category_name,
                category_id,
                {'updated_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='update',
                    user=current_user,
                    category=category,
                    old_values=old_values,
                    new_values=category.to_dict()
                )

            logger.info(f"Category updated successfully")
            return self._enrich_category(category)
        except Exception as e:
            logger.error(f"Error updating category: {e}", exc_info=True)
            raise Exception(f"Error updating category: {str(e)}")

    def soft_delete_category(self, category_id, current_user=None, deletion_context=None):
        """Soft delete category – moves all products to Uncategorized."""
        try:
            logger.info(f"Soft deleting category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return False

            old_values = category.to_dict()

            # Move all products in this category to Uncategorized
            products_moved = self.move_all_products_to_uncategorized(category_id)

            category.soft_delete(deleted_by=current_user.get('username') if current_user else 'system',
                                 reason=deletion_context or "category_deletion")

            # Send notification
            self._send_category_notification(
                'soft_deleted',
                category.category_name,
                category_id,
                {
                    'deleted_by': current_user.get('username') if current_user else 'system',
                    'deletion_context': deletion_context,
                    'products_moved': products_moved
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='soft_delete',
                    user=current_user,
                    category=category,
                    old_values=old_values,
                    details={'deletion_context': deletion_context, 'products_moved': products_moved}
                )

            logger.info(f"Category soft deleted successfully, {products_moved} products moved")
            return True
        except Exception as e:
            logger.error(f"Error soft deleting category: {e}")
            raise Exception(f"Error soft deleting category: {str(e)}")

    def restore_category(self, category_id, current_user=None):
        """Restore a soft-deleted category."""
        try:
            logger.info(f"Restoring category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or not category.isDeleted:
                return False

            category.restore_category(restored_by=current_user.get('username') if current_user else 'system')

            # Send notification
            self._send_category_notification(
                'restored',
                category.category_name,
                category_id,
                {'restored_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='restore',
                    user=current_user,
                    category=category,
                    details={'restored': True}
                )

            logger.info("Category restored successfully")
            return True
        except Exception as e:
            logger.error(f"Error restoring category: {e}")
            raise Exception(f"Error restoring category: {str(e)}")

    def hard_delete_category(self, category_id, current_user=None):
        """Permanently delete category (use with caution)."""
        try:
            logger.warning(f"HARD DELETING category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category:
                return False

            category_name = category.category_name

            # Move all products to Uncategorized before deletion
            products_moved = self.move_all_products_to_uncategorized(category_id)

            category.delete()

            # Send notification
            self._send_category_notification(
                'hard_deleted',
                category_name,
                category_id,
                {
                    'deleted_by': current_user.get('username') if current_user else 'system',
                    'products_moved': products_moved
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='hard_delete',
                    user=current_user,
                    category=category,
                    details={'permanent': True, 'products_moved': products_moved}
                )

            logger.warning(f"Category PERMANENTLY deleted, {products_moved} products moved")
            return True
        except Exception as e:
            logger.error(f"Error hard deleting category: {e}")
            raise Exception(f"Error hard deleting category: {str(e)}")

    def get_deleted_categories(self):
        """Get all soft-deleted categories with product counts."""
        try:
            categories = [c for c in Category.query("categories") if c.isDeleted]
            return [self._enrich_category(cat) for cat in categories]
        except Exception as e:
            logger.error(f"Error getting deleted categories: {e}")
            raise Exception(f"Error getting deleted categories: {str(e)}")

    # -----------------------------------------------------------------
    # SUBCATEGORY OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def add_subcategory(self, category_id, subcategory_data, current_user=None):
        """Add a subcategory to a category."""
        try:
            logger.info(f"Adding subcategory to category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                raise ValueError("Category not found or is deleted")

            subcategory = category.add_subcategory(
                name=subcategory_data.get('name'),
                description=subcategory_data.get('description'),
                icon=subcategory_data.get('icon'),
                sort_order=subcategory_data.get('sort_order', 0),
                status=subcategory_data.get('status', 'active')
            )

            # Send notification
            self._send_category_notification(
                'subcategory_added',
                category.category_name,
                category_id,
                {
                    'subcategory_name': subcategory.name,
                    'subcategory_id': subcategory.subcategory_id,
                    'added_by': current_user.get('username') if current_user else 'system'
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='add_subcategory',
                    user=current_user,
                    category=category,
                    details={
                        'subcategory_name': subcategory.name,
                        'subcategory_id': subcategory.subcategory_id
                    }
                )

            logger.info(f"Subcategory '{subcategory.name}' added successfully")
            return True
        except Exception as e:
            logger.error(f"Error adding subcategory: {e}", exc_info=True)
            raise Exception(f"Error adding subcategory: {str(e)}")

    def remove_subcategory(self, category_id, subcategory_name, current_user=None):
        """Remove a subcategory from a category – moves its products to 'General'."""
        try:
            logger.info(f"Removing subcategory '{subcategory_name}' from category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                raise ValueError("Category not found or is deleted")

            # Find subcategory ID by name
            subcategory = None
            for sc in category.sub_categories:
                if sc.name == subcategory_name:
                    subcategory = sc
                    break

            if not subcategory:
                raise ValueError(f"Subcategory '{subcategory_name}' not found")

            # Check if subcategory has products
            product_count = self._get_product_count_by_subcategory(category.sk, subcategory_name)
            if product_count > 0:
                # Move products to 'General' subcategory
                moved = self.product_collection.update_many(
                    {'category_id': category_id, 'subcategory_name': subcategory_name},
                    {'$set': {'subcategory_name': 'General', 'updated_at': datetime.utcnow()}}
                ).modified_count
                logger.info(f"Moved {moved} products to 'General' subcategory")
            else:
                moved = 0

            success = category.remove_subcategory(subcategory.subcategory_id)
            if success:
                self._send_category_notification(
                    'subcategory_removed',
                    category.category_name,
                    category_id,
                    {
                        'subcategory_name': subcategory_name,
                        'subcategory_id': subcategory.subcategory_id,
                        'removed_by': current_user.get('username') if current_user else 'system',
                        'products_moved': moved
                    }
                )

                # Audit logging
                if current_user and self.audit_service:
                    self._log_category_audit(
                        action='remove_subcategory',
                        user=current_user,
                        category=category,
                        details={
                            'subcategory_name': subcategory_name,
                            'subcategory_id': subcategory.subcategory_id,
                            'products_moved': moved
                        }
                    )

                logger.info(f"Subcategory '{subcategory_name}' removed successfully, {moved} products moved")
                return True
            return False
        except Exception as e:
            logger.error(f"Error removing subcategory: {e}", exc_info=True)
            raise Exception(f"Error removing subcategory: {str(e)}")

    def get_subcategories(self, category_id):
        """Get all subcategories for a category with product counts."""
        try:
            if not self._is_valid_category_id(category_id):
                return []
            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return []
            result = []
            for sc in category.sub_categories:
                sc_dict = sc.to_dict()
                sc_dict['product_count'] = self._get_product_count_by_subcategory(category_id, sc.name)
                result.append(sc_dict)
            return result
        except Exception as e:
            logger.error(f"Error getting subcategories: {e}")
            raise Exception(f"Error getting subcategories: {str(e)}")

    # -----------------------------------------------------------------
    # PRODUCT QUERY METHODS (replacing array-based methods)
    # -----------------------------------------------------------------
    def get_category_product_count(self, category_id):
        """Get total number of products in a category."""
        try:
            return self.product_service._get_product_count_by_category(category_id)
        except Exception as e:
            logger.error(f"Error getting category product count: {e}")
            return 0

    def get_subcategory_product_count(self, category_id, subcategory_name):
        """Get number of products in a specific subcategory."""
        try:
            return self.product_service._get_product_count_by_subcategory(category_id, subcategory_name)
        except Exception as e:
            logger.error(f"Error getting subcategory product count: {e}")
            return 0

    def get_products_in_category(self, category_id, include_deleted=False):
        """Get all products in a category."""
        try:
            products = self.product_service.get_products_by_category(category_id)
            if not include_deleted:
                products = [p for p in products if not p.isDeleted]
            return [p.to_dict() for p in products]
        except Exception as e:
            logger.error(f"Error getting products in category: {e}")
            raise Exception(f"Error getting products in category: {str(e)}")

    def get_products_in_subcategory(self, category_id, subcategory_name, include_deleted=False):
        """Get all products in a specific subcategory."""
        try:
            products = self.product_service._get_products_by_subcategory(category_id, subcategory_name, include_deleted)
            return [p.to_dict() for p in products]
        except Exception as e:
            logger.error(f"Error getting products in subcategory: {e}")
            raise Exception(f"Error getting products in subcategory: {str(e)}")

    def get_category_with_products(self, category_id, include_deleted=False):
        """Get category with all its products organized by subcategory."""
        try:
            category = self.get_category_by_id(category_id, include_deleted)
            if not category:
                return None

            products = self.get_products_in_category(category_id, include_deleted)
            for sub in category.get('sub_categories', []):
                sub['products'] = [
                    p for p in products
                    if p.get('subcategory_name') == sub['name']
                ]
                sub['product_count'] = len(sub['products'])
            return category
        except Exception as e:
            logger.error(f"Error getting category with products: {e}")
            raise Exception(f"Error getting category with products: {str(e)}")

    # -----------------------------------------------------------------
    # PRODUCT MANAGEMENT PROXY METHODS (delegate to product_service)
    # -----------------------------------------------------------------
    def move_product_to_category(self, product_id, new_category_id, new_subcategory_name=None, current_user=None):
        """Proxy method: Move product to a different category."""
        try:
            return self.product_service.move_product_to_category(
                product_id, new_category_id, new_subcategory_name, current_user
            )
        except Exception as e:
            logger.error(f"Error moving product to category: {e}")
            raise Exception(f"Error moving product to category: {str(e)}")

    def move_product_to_subcategory(self, product_id, category_id, subcategory_name, current_user=None):
        """Proxy method: Move product to a different subcategory within the same category."""
        try:
            return self.product_service.move_product_to_subcategory(
                product_id, category_id, subcategory_name, current_user
            )
        except Exception as e:
            logger.error(f"Error moving product to subcategory: {e}")
            raise Exception(f"Error moving product to subcategory: {str(e)}")

    def bulk_move_products_to_category(self, product_ids, new_category_id, new_subcategory_name=None, current_user=None):
        """Proxy method: Bulk move products to a different category."""
        try:
            return self.product_service.bulk_move_products_to_category(
                product_ids, new_category_id, new_subcategory_name, current_user
            )
        except Exception as e:
            logger.error(f"Error bulk moving products: {e}")
            raise Exception(f"Error bulk moving products: {str(e)}")

    def bulk_move_products_to_subcategory(self, product_ids, category_id, subcategory_name, current_user=None):
        """Proxy method: Bulk move products to a different subcategory."""
        try:
            return self.product_service.bulk_move_products_to_subcategory(
                product_ids, category_id, subcategory_name, current_user
            )
        except Exception as e:
            logger.error(f"Error bulk moving products to subcategory: {e}")
            raise Exception(f"Error bulk moving products to subcategory: {str(e)}")

    def move_all_products_to_uncategorized(self, category_id):
        """Move all products from a category to Uncategorized."""
        try:
            return self.product_service.move_all_products_to_uncategorized(category_id)
        except Exception as e:
            logger.error(f"Error moving products to uncategorized: {e}")
            return 0

    # -----------------------------------------------------------------
    # UTILITY AND STATS METHODS
    # -----------------------------------------------------------------
    def get_active_categories(self, include_deleted=False):
        """Get only active categories."""
        try:
            cats = Category.get_active_categories()
            if not include_deleted:
                cats = [c for c in cats if not c.isDeleted]
            return [self._enrich_category(c) for c in cats]
        except Exception as e:
            logger.error(f"Error getting active categories: {e}")
            raise Exception(f"Error getting active categories: {str(e)}")

    def search_categories(self, search_term, include_deleted=False, limit=20):
        """Search categories by name or description."""
        try:
            if not search_term or not search_term.strip():
                return []
            cats = Category.search_categories(search_term, limit=limit)
            if not include_deleted:
                cats = [c for c in cats if not c.isDeleted]
            return [self._enrich_category(c) for c in cats]
        except Exception as e:
            logger.error(f"Error searching categories: {e}")
            raise Exception(f"Error searching categories: {str(e)}")

    def get_category_stats(self):
        """Get comprehensive category statistics."""
        try:
            from ...models.Categories import CategoryManager
            stats = CategoryManager.get_category_statistics()

            total_products = 0
            for cat in Category.get_all_categories(include_deleted=False):
                total_products += self._get_product_count_by_category(cat.sk)

            stats['total_products'] = total_products
            stats['avg_products_per_category'] = total_products / stats['total_categories'] if stats['total_categories'] else 0
            return stats
        except Exception as e:
            logger.error(f"Error getting category stats: {e}")
            return {
                'total_categories': 0,
                'active_categories': 0,
                'deleted_categories': 0,
                'total_subcategories': 0,
                'total_products': 0
            }

    def get_category_delete_info(self, category_id):
        """Get information about a category before deletion."""
        try:
            if not self._is_valid_category_id(category_id):
                return None
            category = Category.get_by_id(category_id)
            if not category:
                return None

            subcategories_count = len(category.sub_categories)
            products_count = self._get_product_count_by_category(category_id)

            return {
                'category_id': category.sk,
                'category_name': category.category_name,
                'description': category.description,
                'status': category.status,
                'isDeleted': category.isDeleted,
                'subcategories_count': subcategories_count,
                'products_count': products_count,
                'can_soft_delete': not category.isDeleted,
                'can_restore': category.isDeleted,
                'created_at': category.date_created.isoformat() if category.date_created else None,
                'last_updated': category.last_updated.isoformat() if category.last_updated else None,
                'deleted_at': category.last_updated.isoformat() if category.isDeleted else None
            }
        except Exception as e:
            logger.error(f"Error getting category delete info: {e}")
            raise Exception(f"Error getting category delete info: {str(e)}")

    def bulk_soft_delete_categories(self, category_ids, current_user=None):
        """Soft delete multiple categories at once."""
        try:
            if not category_ids:
                return {'success': 0, 'failed': 0, 'errors': []}

            logger.info(f"Bulk soft deleting {len(category_ids)} categories")
            success_count = 0
            failed_count = 0
            errors = []

            for cid in category_ids:
                try:
                    if self.soft_delete_category(cid, current_user, "bulk_delete"):
                        success_count += 1
                    else:
                        failed_count += 1
                        errors.append(f"Failed to soft delete {cid}")
                except Exception as e:
                    failed_count += 1
                    errors.append(f"Error deleting {cid}: {str(e)}")

            if success_count > 0:
                self._send_category_notification(
                    'bulk_deleted',
                    f"{success_count} categories",
                    None,
                    {
                        'success_count': success_count,
                        'failed_count': failed_count,
                        'action_type': 'categories_bulk_delete'
                    }
                )

            return {
                'success': success_count,
                'failed': failed_count,
                'errors': errors,
                'total_requested': len(category_ids)
            }
        except Exception as e:
            logger.error(f"Error in bulk soft delete: {e}")
            raise Exception(f"Error in bulk soft delete: {str(e)}")

    def bulk_update_categories_status(self, category_ids, new_status, current_user=None):
        """Efficiently update multiple categories status."""
        try:
            if new_status not in ['active', 'inactive']:
                raise ValueError("Status must be 'active' or 'inactive'")

            logger.info(f"Bulk updating {len(category_ids)} categories to status: {new_status}")

            success_count = 0
            failed_count = 0
            errors = []

            for cid in category_ids:
                try:
                    cat = Category.get_by_id(cid)
                    if cat and not cat.isDeleted:
                        cat.update_category(status=new_status)
                        success_count += 1
                    else:
                        failed_count += 1
                        errors.append(f"Category {cid} not found or deleted")
                except Exception as e:
                    failed_count += 1
                    errors.append(f"Error updating {cid}: {str(e)}")

            if success_count > 0:
                self._send_category_notification(
                    'bulk_updated',
                    f"{success_count} categories",
                    None,
                    {
                        'success_count': success_count,
                        'new_status': new_status,
                        'action_type': 'categories_bulk_status_update'
                    }
                )

            return {
                'success': success_count,
                'total_requested': len(category_ids)
            }
        except Exception as e:
            logger.error(f"Bulk update failed: {e}")
            raise Exception(f"Bulk update failed: {str(e)}")

    # -----------------------------------------------------------------
    # SYSTEM INITIALIZATION (preserved)
    # -----------------------------------------------------------------
    def ensure_uncategorized_category_exists(self):
        """Ensure an 'Uncategorized' category exists."""
        try:
            uncat = Category.get_by_name('Uncategorized')
            if uncat:
                # Ensure it has at least the 'General' subcategory
                if not any(sc.name == self.DEFAULT_SUBCATEGORY_NAME for sc in uncat.sub_categories):
                    uncat.add_subcategory(
                        name=self.DEFAULT_SUBCATEGORY_NAME,
                        description="Default holding subcategory for uncategorized products"
                    )
                logger.info("Uncategorized category already exists")
                return uncat.to_dict()

            # Create default uncategorized category with fixed ID CAT-0001
            now = datetime.utcnow()
            uncat = Category(
                pk="categories",
                sk="CAT-0001",
                category_name="Uncategorized",
                description="Default category for products without specific categorization",
                status="active",
                sort_order=9999,
                sub_categories=[],
                isDeleted=False,
                date_created=now,
                last_updated=now
            )
            uncat.save()

            # Add default 'General' subcategory
            uncat.add_subcategory(
                name=self.DEFAULT_SUBCATEGORY_NAME,
                description="Default holding subcategory for uncategorized products"
            )

            logger.info(f"Created default 'Uncategorized' category with ID: CAT-0001")
            self._send_category_notification(
                'created',
                'Uncategorized',
                "CAT-0001",
                {'system_generated': True, 'action_type': 'system_initialization'}
            )

            return uncat.to_dict()
        except Exception as e:
            logger.error(f"Error ensuring uncategorized category exists: {e}")
            raise Exception(f"Error creating uncategorized category: {str(e)}")

    # -----------------------------------------------------------------
    # PRIVATE HELPERS (for DynamoDB implementation)
    # -----------------------------------------------------------------
    def _validate_category_data(self, category_data):
        """Validate category data (preserved from original)."""
        if not category_data:
            raise ValueError("Category data is required")
        category_name = category_data.get("category_name", "").strip()
        if not category_name:
            raise ValueError("Category name is required")
        existing = Category.get_by_name(category_name)
        if existing:
            raise ValueError(f"Category '{category_name}' already exists")
        status = category_data.get("status", "active")
        if status not in ['active', 'inactive']:
            raise ValueError("Status must be 'active' or 'inactive'")
        return category_name

    def _enrich_category(self, category):
        """Add product counts to category dict."""
        cat_dict = category.to_dict()
        cid = category.sk
        cat_dict['product_count'] = self._get_product_count_by_category(cid)
        for sub in cat_dict.get('sub_categories', []):
            sub['product_count'] = self._get_product_count_by_subcategory(cid, sub['name'])
        return cat_dict

    def _get_product_count_by_category(self, category_id):
        """Count products in a category using product_service."""
        return self.product_service._get_product_count_by_category(category_id)

    def _get_product_count_by_subcategory(self, category_id, subcategory_name):
        """Count products in a subcategory using product_service."""
        return self.product_service._get_product_count_by_subcategory(category_id, subcategory_name)

    def _log_category_audit(self, action, user, category, old_values=None, new_values=None, details=None):
        """Log category audit event."""
        try:
            import json
            changes = None
            if old_values or new_values:
                changes = json.dumps({
                    "old_values": self._convert_to_serializable(old_values) or {},
                    "new_values": self._convert_to_serializable(new_values) or {},
                    "changed_fields": list(new_values.keys()) if new_values else []
                })
            self.audit_service._create_audit_log(
                event_type=f"category_{action}",
                user_data=user,
                target_data={
                    "type": "category",
                    "id": category.sk,
                    "name": category.category_name
                },
                old_values=old_values,
                new_values=new_values,
                metadata=details,
                changes=changes
            )
        except Exception as e:
            logger.error(f"Failed to log category audit: {e}")

    def _convert_to_serializable(self, obj):
        """Convert object to JSON serializable format."""
        if isinstance(obj, dict):
            return {k: self._convert_to_serializable(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [self._convert_to_serializable(i) for i in obj]
        if isinstance(obj, datetime):
            return obj.isoformat()
        return obj