"""
Category Service - DynamoDB implementation using PynamoDB.
Full audit & notification integration.
All method names and signatures match original MongoDB service.
"""
from datetime import datetime
from typing import List, Dict, Any, Optional
import logging
import json
from decimal import Decimal

from ...models.Categories import Category, CategoryManager, validate_category_id
from ...models.Product import Product, validate_product_id
from services.audit_service import AuditLogService
from services.notification_service import notification_service

logger = logging.getLogger(__name__)

class CategoryService:
    """
    Complete DynamoDB-based Category Service.
    Exact replica of original MongoDB service method signatures.
    """

    VALID_CATEGORY_PREFIXES = ('CAT-',)  # Updated for DynamoDB format
    UNCATEGORIZED_ID_CANDIDATES = ['CAT-0001']  # Single canonical ID
    DEFAULT_SUBCATEGORY_NAME = 'None'

    def __init__(self):
        """Initialize with DynamoDB and audit/notification services."""
        self.audit_service = AuditLogService()
        self._ensure_tables_exist()
        self.ensure_uncategorized_category_exists()

    # -----------------------------------------------------------------
    # TABLE INITIALIZATION
    # -----------------------------------------------------------------
    def _ensure_tables_exist(self):
        """Create DynamoDB tables if not exist."""
        try:
            if not Category.exists():
                Category.create_table(wait=True)
                logger.info("Category table created")
            if not Product.exists():
                Product.create_table(wait=True)
                logger.info("Product table created")
        except Exception as e:
            logger.error(f"Error ensuring tables: {e}")

    # -----------------------------------------------------------------
    # UTILITY METHODS (preserved signatures)
    # -----------------------------------------------------------------
    def _is_valid_category_id(self, category_id):
        """Check if category ID format is valid (CAT-####)."""
        return validate_category_id(category_id)

    def _ensure_subcategory_present(self, category_id, category_doc, subcategory_name):
        """
        Legacy method – ensures a subcategory exists.
        category_doc is kept for signature compatibility but not used.
        """
        category = Category.get_by_id(category_id)
        if not category:
            return
        if not any(sc.name == subcategory_name for sc in category.sub_categories):
            category.add_subcategory(
                name=subcategory_name,
                description=f'Default {subcategory_name} subcategory'
            )

    def generate_category_id(self):
        """
        Generate next CAT-#### ID.
        NOTE: In DynamoDB, IDs are generated by the model automatically.
        This method is kept for compatibility; actual creation uses model's generate_sk.
        """
        # For direct calls, we simulate generation
        from app.utils import generate_sk
        return generate_sk('CAT-', 'category_seq')

    def generate_subcategory_id(self):
        """Generate next SUB-##### ID."""
        from app.utils import generate_sk
        return generate_sk('SUB-', 'subcategory_seq')

    def _send_category_notification(self, action_type, category_name, category_id=None, additional_metadata=None):
        """Send notification for category actions."""
        templates = {
            'created':          {'title': 'Category Created',          'priority': 'medium'},
            'updated':          {'title': 'Category Updated',         'priority': 'medium'},
            'soft_deleted':     {'title': 'Category Deleted',         'priority': 'medium'},
            'hard_deleted':     {'title': 'Category Permanently Deleted', 'priority': 'high'},
            'restored':         {'title': 'Category Restored',        'priority': 'medium'},
            'bulk_deleted':     {'title': 'Categories Bulk Deleted',  'priority': 'low'},
            'bulk_updated':     {'title': 'Categories Bulk Updated',  'priority': 'low'},
            'subcategory_added':   {'title': 'Subcategory Added',     'priority': 'low'},
            'subcategory_removed': {'title': 'Subcategory Removed',   'priority': 'low'},
            'subcategory_updated': {'title': 'Subcategory Updated',   'priority': 'low'},
            'product_added':    {'title': 'Product Added to Category', 'priority': 'low'},
            'product_removed':  {'title': 'Product Removed from Category', 'priority': 'low'},
            'product_moved':    {'title': 'Product Moved',            'priority': 'low'},
        }
        tpl = templates.get(action_type)
        if not tpl:
            return
        metadata = {
            "category_id": str(category_id) if category_id else "",
            "category_name": category_name,
            "action_type": f"category_{action_type}",
            **(additional_metadata or {})
        }
        notification_service.create_notification(
            title=tpl['title'],
            message=f"{tpl['title']}: {category_name}" if category_name else tpl['title'],
            priority=tpl['priority'],
            notification_type="system",
            metadata=metadata,
            action_type=f"category_{action_type}"
        )

    # -----------------------------------------------------------------
    # CORE CATEGORY OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def create_category(self, category_data, current_user=None):
        """Create a new category."""
        try:
            category_name = self._validate_category_data(category_data)
            logger.info(f"Creating category: {category_name}")

            # Use model to create category
            category = Category.create_category(
                category_name=category_name,
                description=category_data.get("description"),
                icon=category_data.get("icon"),
                sort_order=category_data.get("sort_order", 0)
            )

            # Add image fields if present (for compatibility)
            image_fields = ['image_url', 'image_filename', 'image_size', 'image_type', 'image_uploaded_at']
            for field in image_fields:
                if field in category_data and category_data[field] is not None:
                    setattr(category, field, category_data[field])
            category.save()

            # Send notification
            self._send_category_notification(
                'created',
                category.category_name,
                category.sk,
                {'created_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='create',
                    user=current_user,
                    category=category,
                    details={'category_data': category_data}
                )

            logger.info(f"Category '{category_name}' created with ID {category.sk}")
            return self._add_product_counts_to_category(category)

        except Exception as e:
            logger.error(f"Error creating category: {e}", exc_info=True)
            raise Exception(f"Error creating category: {str(e)}")

    def get_all_categories(self, include_deleted=False, limit=None, skip=None):
        """Get all categories with product counts."""
        try:
            categories = Category.get_all_categories(include_deleted=include_deleted)
            if skip:
                categories = categories[skip:]
            if limit:
                categories = categories[:limit]

            # Add product counts for each subcategory
            result = []
            for cat in categories:
                cat_dict = self._add_product_counts_to_category(cat)
                result.append(cat_dict)
            return result
        except Exception as e:
            logger.error(f"Error getting categories: {e}")
            raise Exception(f"Error getting categories: {str(e)}")

    def get_category_by_id(self, category_id, include_deleted=False):
        """Get category by ID with product counts."""
        try:
            if not self._is_valid_category_id(category_id):
                return None

            category = Category.get_by_id(category_id)
            if not category:
                return None
            if not include_deleted and category.isDeleted:
                return None

            # Add product counts
            return self._add_product_counts_to_category(category)
        except Exception as e:
            logger.error(f"Error getting category by ID {category_id}: {e}")
            raise Exception(f"Error getting category: {str(e)}")

    def update_category(self, category_id, category_data, current_user=None):
        """Update category."""
        try:
            logger.info(f"Updating category {category_id}")
            if not self._is_valid_category_id(category_id):
                return None

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return None

            old_values = category.to_dict()

            # Validate category name if being updated
            if 'category_name' in category_data:
                new_name = category_data['category_name'].strip()
                if new_name != category.category_name:
                    existing = Category.get_by_name(new_name)
                    if existing and existing.sk != category.sk:
                        raise ValueError(f"Category name '{new_name}' already exists")

            # Update allowed fields
            allowed_fields = {'category_name', 'description', 'status', 'sort_order', 'icon'}
            updates = {k: v for k, v in category_data.items() if k in allowed_fields}
            category.update_category(**updates)

            # Update image fields if present
            image_fields = ['image_url', 'image_filename', 'image_size', 'image_type', 'image_uploaded_at']
            for field in image_fields:
                if field in category_data:
                    setattr(category, field, category_data[field])
            category.save()

            # Send notification
            self._send_category_notification(
                'updated',
                category.category_name,
                category_id,
                {'updated_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='update',
                    user=current_user,
                    category=category,
                    old_values=old_values,
                    new_values=category.to_dict()
                )

            logger.info(f"Category updated successfully")
            return self._add_product_counts_to_category(category)
        except Exception as e:
            logger.error(f"Error updating category: {e}", exc_info=True)
            raise Exception(f"Error updating category: {str(e)}")

    def soft_delete_category(self, category_id, current_user=None, deletion_context=None):
        """Soft delete category."""
        try:
            logger.info(f"Soft deleting category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return False

            old_values = category.to_dict()
            category.soft_delete()

            # Send notification
            self._send_category_notification(
                'soft_deleted',
                category.category_name,
                category_id,
                {
                    'deleted_by': current_user.get('username') if current_user else 'system',
                    'deletion_context': deletion_context
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='soft_delete',
                    user=current_user,
                    category=category,
                    old_values=old_values,
                    details={'deletion_context': deletion_context}
                )

            logger.info("Category soft deleted successfully")
            return True
        except Exception as e:
            logger.error(f"Error soft deleting category: {e}")
            raise Exception(f"Error soft deleting category: {str(e)}")

    def restore_category(self, category_id, current_user=None):
        """Restore a soft-deleted category."""
        try:
            logger.info(f"Restoring category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or not category.isDeleted:
                return False

            category.restore_category()

            # Send notification
            self._send_category_notification(
                'restored',
                category.category_name,
                category_id,
                {'restored_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='restore',
                    user=current_user,
                    category=category,
                    details={'restored': True}
                )

            logger.info("Category restored successfully")
            return True
        except Exception as e:
            logger.error(f"Error restoring category: {e}")
            raise Exception(f"Error restoring category: {str(e)}")

    def hard_delete_category(self, category_id, current_user=None):
        """Permanently delete category (use with caution)."""
        try:
            logger.warning(f"HARD DELETING category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category:
                return False

            category_name = category.category_name
            category.delete()

            # Send notification
            self._send_category_notification(
                'hard_deleted',
                category_name,
                category_id,
                {'deleted_by': current_user.get('username') if current_user else 'system'}
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='hard_delete',
                    user=current_user,
                    category=category,
                    details={'permanent': True}
                )

            logger.warning("Category PERMANENTLY deleted")
            return True
        except Exception as e:
            logger.error(f"Error hard deleting category: {e}")
            raise Exception(f"Error hard deleting category: {str(e)}")

    def get_deleted_categories(self):
        """Get all soft-deleted categories with product counts."""
        try:
            categories = [c for c in Category.query("categories") if c.isDeleted]
            result = []
            for cat in categories:
                cat_dict = self._add_product_counts_to_category(cat)
                result.append(cat_dict)
            return result
        except Exception as e:
            logger.error(f"Error getting deleted categories: {e}")
            raise Exception(f"Error getting deleted categories: {str(e)}")

    # -----------------------------------------------------------------
    # SUBCATEGORY OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def add_subcategory(self, category_id, subcategory_data, current_user=None):
        """Add a subcategory to a category."""
        try:
            logger.info(f"Adding subcategory to category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                raise ValueError("Category not found or is deleted")

            subcategory = category.add_subcategory(
                name=subcategory_data.get('name'),
                description=subcategory_data.get('description'),
                icon=subcategory_data.get('icon'),
                sort_order=subcategory_data.get('sort_order', 0),
                status=subcategory_data.get('status', 'active')
            )

            # Send notification
            self._send_category_notification(
                'subcategory_added',
                category.category_name,
                category_id,
                {
                    'subcategory_name': subcategory.name,
                    'subcategory_id': subcategory.subcategory_id,
                    'added_by': current_user.get('username') if current_user else 'system'
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_category_audit(
                    action='add_subcategory',
                    user=current_user,
                    category=category,
                    details={
                        'subcategory_name': subcategory.name,
                        'subcategory_id': subcategory.subcategory_id
                    }
                )

            logger.info(f"Subcategory '{subcategory.name}' added successfully")
            return True
        except Exception as e:
            logger.error(f"Error adding subcategory: {e}", exc_info=True)
            raise Exception(f"Error adding subcategory: {str(e)}")

    def remove_subcategory(self, category_id, subcategory_name, current_user=None):
        """Remove a subcategory from a category (by name)."""
        try:
            logger.info(f"Removing subcategory '{subcategory_name}' from category {category_id}")
            if not self._is_valid_category_id(category_id):
                return False

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                raise ValueError("Category not found or is deleted")

            # Find subcategory ID by name
            subcategory = None
            for sc in category.sub_categories:
                if sc.name == subcategory_name:
                    subcategory = sc
                    break

            if not subcategory:
                raise ValueError(f"Subcategory '{subcategory_name}' not found")

            # Check if subcategory has products (using Product model)
            product_count = self._get_product_count_by_subcategory(category.sk, subcategory_name)
            if product_count > 0:
                raise ValueError(f"Cannot remove subcategory '{subcategory_name}' - it contains {product_count} products")

            success = category.remove_subcategory(subcategory.subcategory_id)
            if success:
                self._send_category_notification(
                    'subcategory_removed',
                    category.category_name,
                    category_id,
                    {
                        'subcategory_name': subcategory_name,
                        'subcategory_id': subcategory.subcategory_id,
                        'removed_by': current_user.get('username') if current_user else 'system'
                    }
                )

                # Audit logging
                if current_user and self.audit_service:
                    self._log_category_audit(
                        action='remove_subcategory',
                        user=current_user,
                        category=category,
                        details={
                            'subcategory_name': subcategory_name,
                            'subcategory_id': subcategory.subcategory_id
                        }
                    )

                logger.info(f"Subcategory '{subcategory_name}' removed successfully")
                return True
            return False
        except Exception as e:
            logger.error(f"Error removing subcategory: {e}", exc_info=True)
            raise Exception(f"Error removing subcategory: {str(e)}")

    def get_subcategories(self, category_id):
        """Get all subcategories for a category."""
        try:
            if not self._is_valid_category_id(category_id):
                return []
            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                return []
            return [sc.to_dict() for sc in category.sub_categories]
        except Exception as e:
            logger.error(f"Error getting subcategories: {e}")
            raise Exception(f"Error getting subcategories: {str(e)}")

    # -----------------------------------------------------------------
    # PRODUCT-CATEGORY RELATIONSHIPS (exact original signatures)
    # -----------------------------------------------------------------
    def _resolve_product(self, product_identifier):
        """Resolve product identifier to get both string ID and name."""
        try:
            product = self._get_product_by_identifier(product_identifier)
            if not product:
                raise ValueError(f"Product not found: {product_identifier}")
            return {
                'id': product.sk,
                'name': product.product_name
            }
        except Exception as e:
            raise ValueError(f"Failed to resolve product: {str(e)}")

    def add_product_to_subcategory(self, category_id, subcategory_name, product_identifier, current_user=None):
        """Add product to subcategory."""
        try:
            logger.info(f"Adding product '{product_identifier}' to subcategory '{subcategory_name}' in category {category_id}")

            if not self._is_valid_category_id(category_id):
                raise ValueError("Invalid category ID")

            product = self._get_product_by_identifier(product_identifier)
            if not product:
                raise ValueError(f"Product '{product_identifier}' not found")

            category = Category.get_by_id(category_id)
            if not category or category.isDeleted:
                raise ValueError("Category not found or deleted")

            # Check if subcategory exists
            if not any(sc.name == subcategory_name for sc in category.sub_categories):
                if subcategory_name == self.DEFAULT_SUBCATEGORY_NAME:
                    self._ensure_subcategory_present(category_id, None, subcategory_name)
                    category = Category.get_by_id(category_id)  # refresh
                else:
                    raise ValueError(f"Subcategory '{subcategory_name}' not found in category")

            # Update product category
            success = self._update_product_category(
                product_id=product.sk,
                category_id=category_id,
                subcategory_name=subcategory_name,
                current_user=current_user
            )
            if not success:
                raise Exception("Failed to update product category")

            # Send notification
            self._send_category_notification(
                'product_added',
                category.category_name,
                category_id,
                {
                    'subcategory_name': subcategory_name,
                    'product_id': product.sk,
                    'product_name': product.product_name,
                    'added_by': current_user.get('username') if current_user else 'system'
                }
            )

            # Audit logging
            if current_user and self.audit_service:
                self._log_product_category_audit(
                    action='add_product_to_subcategory',
                    user=current_user,
                    category=category,
                    product=product,
                    details={'subcategory_name': subcategory_name, 'action': 'added'}
                )

            return {
                'success': True,
                'action': 'added',
                'product_id': product.sk,
                'product_name': product.product_name,
                'category_id': category_id,
                'subcategory_name': subcategory_name,
                'message': f"Product '{product.product_name}' added to subcategory '{subcategory_name}'"
            }
        except Exception as e:
            logger.error(f"Error adding product to subcategory: {e}")
            raise Exception(f"Error adding product to subcategory: {str(e)}")

    def _remove_product_from_all_subcategories(self, product_id):
        """
        Remove product from all subcategories.
        In DynamoDB, we simply update the product to have no category.
        """
        product = Product.get_by_id(product_id)
        if product:
            product.update_product(category_id=None, subcategory_name=None)
            logger.info(f"Removed product {product_id} from all subcategories")

    def remove_product_from_subcategory(self, category_id, subcategory_name, product_identifier, current_user=None):
        """Remove product from subcategory."""
        try:
            logger.info(f"Removing product '{product_identifier}' from subcategory '{subcategory_name}' in category {category_id}")

            if not self._is_valid_category_id(category_id):
                raise ValueError("Invalid category ID")

            product = self._get_product_by_identifier(product_identifier)
            if not product:
                raise ValueError(f"Product '{product_identifier}' not found")

            # Verify product is in this category/subcategory
            if product.category_id != category_id or product.subcategory_name != subcategory_name:
                return {
                    'success': False,
                    'message': 'Product not found in specified category/subcategory'
                }

            # Remove category reference
            success = self._update_product_category(
                product_id=product.sk,
                category_id=None,
                subcategory_name=None,
                current_user=current_user
            )
            if not success:
                raise Exception("Failed to remove product from category")

            category = Category.get_by_id(category_id)
            cat_name = category.category_name if category else "Unknown"

            self._send_category_notification(
                'product_removed',
                cat_name,
                category_id,
                {
                    'subcategory_name': subcategory_name,
                    'product_id': product.sk,
                    'product_name': product.product_name,
                    'removed_by': current_user.get('username') if current_user else 'system'
                }
            )

            if current_user and self.audit_service:
                self._log_product_category_audit(
                    action='remove_product_from_subcategory',
                    user=current_user,
                    category=category,
                    product=product,
                    details={'subcategory_name': subcategory_name, 'action': 'removed'}
                )

            return {
                'success': True,
                'action': 'removed',
                'product_id': product.sk,
                'product_name': product.product_name,
                'category_id': category_id,
                'subcategory_name': subcategory_name,
                'message': f"Product '{product.product_name}' removed from subcategory '{subcategory_name}'"
            }
        except Exception as e:
            logger.error(f"Error removing product from subcategory: {e}")
            raise Exception(f"Error removing product from subcategory: {str(e)}")

    def get_products_in_subcategory(self, category_id, subcategory_name, include_deleted=False):
        """Get all products in a specific subcategory."""
        try:
            products = self._get_products_by_subcategory(category_id, subcategory_name, include_deleted)
            return [p.to_dict() for p in products]
        except Exception as e:
            logger.error(f"Error getting products in subcategory: {e}")
            raise Exception(f"Error getting products in subcategory: {str(e)}")

    def get_subcategory_products_with_details(self, category_id, subcategory_name):
        """Get products in subcategory with full product details (ID + Name format)."""
        try:
            products = self._get_products_by_subcategory(category_id, subcategory_name, include_deleted=False)
            return [
                {
                    'product_id': p.sk,
                    'product_name': p.product_name
                }
                for p in products
            ]
        except Exception as e:
            logger.error(f"Error getting subcategory products: {e}")
            raise Exception(f"Error getting subcategory products: {str(e)}")

    def move_product_to_none_subcategory(self, product_id, category_id, current_user=None):
        """Move product to the default 'None' subcategory within the same category."""
        try:
            logger.info(f"Moving product {product_id} to '{self.DEFAULT_SUBCATEGORY_NAME}' subcategory in category {category_id}")

            if not validate_product_id(product_id) or not self._is_valid_category_id(category_id):
                raise ValueError("Invalid product or category ID format")

            product = Product.get_by_id(product_id)
            if not product:
                raise ValueError(f"Product {product_id} not found")

            # Ensure 'None' subcategory exists
            category = Category.get_by_id(category_id)
            if not category:
                raise ValueError(f"Category {category_id} not found")
            self._ensure_subcategory_present(category_id, None, self.DEFAULT_SUBCATEGORY_NAME)

            # Update product
            success = self._update_product_category(
                product_id=product_id,
                category_id=category_id,
                subcategory_name=self.DEFAULT_SUBCATEGORY_NAME,
                current_user=current_user
            )
            if not success:
                raise Exception("Failed to move product")

            return {
                'success': True,
                'action': 'moved_to_default',
                'message': f"Product '{product.product_name}' moved to '{self.DEFAULT_SUBCATEGORY_NAME}' subcategory"
            }
        except Exception as e:
            logger.error(f"Error moving product to None subcategory: {e}")
            raise Exception(f"Error moving product to None subcategory: {str(e)}")

    def move_product_to_category(self, product_id, new_category_id, new_subcategory_name=None, current_user=None):
        """Move a product to a different category/subcategory."""
        try:
            logger.info(f"Moving product {product_id} to category {new_category_id}")

            product = Product.get_by_id(product_id)
            if not product:
                raise ValueError(f"Product {product_id} not found")

            target_category = Category.get_by_id(new_category_id)
            if not target_category:
                raise ValueError(f"Target category {new_category_id} not found")

            new_sub = new_subcategory_name or self.DEFAULT_SUBCATEGORY_NAME

            # Ensure subcategory exists
            if not any(sc.name == new_sub for sc in target_category.sub_categories):
                if new_sub == self.DEFAULT_SUBCATEGORY_NAME:
                    self._ensure_subcategory_present(new_category_id, None, new_sub)
                else:
                    raise ValueError(f"Subcategory '{new_sub}' not found in category {new_category_id}")

            old_cat = product.category_id
            old_sub = product.subcategory_name

            success = self._update_product_category(
                product_id=product_id,
                category_id=new_category_id,
                subcategory_name=new_sub,
                current_user=current_user
            )
            if not success:
                raise Exception("Failed to move product")

            self._send_category_notification(
                'product_moved',
                target_category.category_name,
                new_category_id,
                {
                    'product_id': product_id,
                    'product_name': product.product_name,
                    'from_category': old_cat,
                    'from_subcategory': old_sub,
                    'to_subcategory': new_sub
                }
            )

            return {
                'success': True,
                'product_id': product_id,
                'product_name': product.product_name,
                'old_category': old_cat,
                'old_subcategory': old_sub,
                'new_category': new_category_id,
                'new_subcategory': new_sub
            }
        except Exception as e:
            logger.error(f"Error moving product to category: {e}")
            raise Exception(f"Error moving product to category: {str(e)}")

    def bulk_move_products_to_category(self, product_ids, new_category_id, new_subcategory_name=None, current_user=None):
        """Bulk move multiple products to a different category/subcategory."""
        try:
            logger.info(f"Bulk moving {len(product_ids)} products to category {new_category_id}")

            target_category = Category.get_by_id(new_category_id)
            if not target_category:
                raise ValueError(f"Target category {new_category_id} not found")

            new_sub = new_subcategory_name or self.DEFAULT_SUBCATEGORY_NAME

            if not any(sc.name == new_sub for sc in target_category.sub_categories):
                if new_sub == self.DEFAULT_SUBCATEGORY_NAME:
                    self._ensure_subcategory_present(new_category_id, None, new_sub)
                else:
                    raise ValueError(f"Subcategory '{new_sub}' not found in category {new_category_id}")

            moved_count = 0
            errors = []

            for pid in product_ids:
                try:
                    result = self.move_product_to_category(pid, new_category_id, new_sub, current_user)
                    if result.get('success'):
                        moved_count += 1
                    else:
                        errors.append(f"Failed to move product {pid}")
                except Exception as e:
                    errors.append(f"Error moving product {pid}: {str(e)}")

            return moved_count  # original returns int count
        except Exception as e:
            logger.error(f"Error bulk moving products: {e}")
            raise Exception(f"Error bulk moving products: {str(e)}")

    # -----------------------------------------------------------------
    # QUERY OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def get_active_categories(self, include_deleted=False):
        """Get only active categories with product counts."""
        try:
            categories = Category.get_active_categories()
            if not include_deleted:
                categories = [c for c in categories if not c.isDeleted]
            result = [self._add_product_counts_to_category(c) for c in categories]
            return result
        except Exception as e:
            logger.error(f"Error getting active categories: {e}")
            raise Exception(f"Error getting active categories: {str(e)}")

    def search_categories(self, search_term, include_deleted=False, limit=20):
        """Search categories by name or description with product counts."""
        try:
            if not search_term or not search_term.strip():
                return []
            categories = Category.search_categories(search_term, limit=limit)
            if not include_deleted:
                categories = [c for c in categories if not c.isDeleted]
            result = [self._add_product_counts_to_category(c) for c in categories]
            return result
        except Exception as e:
            logger.error(f"Error searching categories: {e}")
            raise Exception(f"Error searching categories: {str(e)}")

    def get_category_product_count(self, category_id):
        """Get total number of products in a category."""
        try:
            return self._get_product_count_by_category(category_id)
        except Exception as e:
            logger.error(f"Error getting category product count: {e}")
            return 0

    def get_subcategory_product_count(self, category_id, subcategory_name):
        """Get number of products in a specific subcategory."""
        try:
            return self._get_product_count_by_subcategory(category_id, subcategory_name)
        except Exception as e:
            logger.error(f"Error getting subcategory product count: {e}")
            return 0

    def get_category_stats(self):
        """Get comprehensive category statistics."""
        try:
            stats = CategoryManager.get_category_statistics()

            categories = Category.get_all_categories(include_deleted=False)
            total_products = 0
            for cat in categories:
                pc = self._get_product_count_by_category(cat.sk)
                total_products += pc

            stats['total_products'] = total_products
            stats['avg_products_per_category'] = total_products / len(categories) if categories else 0

            return stats
        except Exception as e:
            logger.error(f"Error getting category stats: {e}")
            return {
                'total_categories': 0,
                'active_categories': 0,
                'deleted_categories': 0,
                'total_subcategories': 0,
                'total_products': 0
            }

    def get_category_delete_info(self, category_id):
        """Get information about a category before deletion."""
        try:
            if not self._is_valid_category_id(category_id):
                return None
            category = Category.get_by_id(category_id)
            if not category:
                return None

            subcategories_count = len(category.sub_categories)
            products_count = self._get_product_count_by_category(category_id)

            return {
                'category_id': category.sk,
                'category_name': category.category_name,
                'description': category.description,
                'status': category.status,
                'isDeleted': category.isDeleted,
                'subcategories_count': subcategories_count,
                'products_count': products_count,
                'can_soft_delete': not category.isDeleted,
                'can_restore': category.isDeleted,
                'created_at': category.date_created.isoformat() if category.date_created else None,
                'last_updated': category.last_updated.isoformat() if category.last_updated else None,
                'deleted_at': category.last_updated.isoformat() if category.isDeleted else None
            }
        except Exception as e:
            logger.error(f"Error getting category delete info: {e}")
            raise Exception(f"Error getting category delete info: {str(e)}")

    def get_category_hierarchy(self):
        """Get full category hierarchy with product counts."""
        try:
            hierarchy = Category.get_category_hierarchy()
            for cat_data in hierarchy['categories']:
                cid = cat_data['category_id']
                cat_data['product_count'] = self._get_product_count_by_category(cid)
                for sub in cat_data['subcategories']:
                    sub['product_count'] = self._get_product_count_by_subcategory(cid, sub['name'])
            return hierarchy
        except Exception as e:
            logger.error(f"Error getting category hierarchy: {e}")
            return {"categories": [], "total_categories": 0, "total_subcategories": 0}

    def get_category_tree(self):
        """Get hierarchical category tree for navigation."""
        try:
            return CategoryManager.get_category_tree()
        except Exception as e:
            logger.error(f"Error getting category tree: {e}")
            return {"tree": [], "total_categories": 0, "total_subcategories": 0}

    # -----------------------------------------------------------------
    # BULK OPERATIONS (exact original signatures)
    # -----------------------------------------------------------------
    def bulk_soft_delete_categories(self, category_ids, current_user=None):
        """Soft delete multiple categories at once."""
        try:
            if not category_ids:
                return {'success': 0, 'failed': 0, 'errors': []}

            logger.info(f"Bulk soft deleting {len(category_ids)} categories")
            success_count = 0
            failed_count = 0
            errors = []

            for cid in category_ids:
                try:
                    if self.soft_delete_category(cid, current_user, "bulk_delete"):
                        success_count += 1
                    else:
                        failed_count += 1
                        errors.append(f"Failed to soft delete {cid}")
                except Exception as e:
                    failed_count += 1
                    errors.append(f"Error deleting {cid}: {str(e)}")

            if success_count > 0:
                self._send_category_notification(
                    'bulk_deleted',
                    f"{success_count} categories",
                    None,
                    {
                        'success_count': success_count,
                        'failed_count': failed_count,
                        'action_type': 'categories_bulk_delete'
                    }
                )

            return {
                'success': success_count,
                'failed': failed_count,
                'errors': errors,
                'total_requested': len(category_ids)
            }
        except Exception as e:
            logger.error(f"Error in bulk soft delete: {e}")
            raise Exception(f"Error in bulk soft delete: {str(e)}")

    def bulk_update_categories_status(self, category_ids, new_status, current_user=None):
        """Efficiently update multiple categories status."""
        try:
            if new_status not in ['active', 'inactive']:
                raise ValueError("Status must be 'active' or 'inactive'")

            logger.info(f"Bulk updating {len(category_ids)} categories to status: {new_status}")

            success_count = 0
            failed_count = 0
            errors = []

            for cid in category_ids:
                try:
                    cat = Category.get_by_id(cid)
                    if cat:
                        cat.update_category(status=new_status)
                        success_count += 1
                    else:
                        failed_count += 1
                        errors.append(f"Category {cid} not found")
                except Exception as e:
                    failed_count += 1
                    errors.append(f"Error updating {cid}: {str(e)}")

            if success_count > 0:
                self._send_category_notification(
                    'bulk_updated',
                    f"{success_count} categories",
                    None,
                    {
                        'success_count': success_count,
                        'new_status': new_status,
                        'action_type': 'categories_bulk_status_update'
                    }
                )

            return {
                'success': success_count,
                'total_requested': len(category_ids)
            }
        except Exception as e:
            logger.error(f"Bulk update failed: {e}")
            raise Exception(f"Bulk update failed: {str(e)}")

    # -----------------------------------------------------------------
    # SYSTEM INITIALIZATION (preserved)
    # -----------------------------------------------------------------
    def ensure_uncategorized_category_exists(self):
        """Ensure an 'Uncategorized' category exists."""
        try:
            uncat = Category.get_by_name('Uncategorized')
            if uncat:
                self._ensure_subcategory_present(uncat.sk, None, self.DEFAULT_SUBCATEGORY_NAME)
                logger.info("Uncategorized category already exists")
                return uncat.to_dict()

            # Create default uncategorized category with ID CAT-0001
            from app.utils import generate_sk
            sk = "CAT-0001"  # fixed ID for uncategorized
            now = datetime.utcnow()
            uncat = Category(
                pk="categories",
                sk=sk,
                category_name="Uncategorized",
                description="Default category for products without specific categorization",
                status="active",
                sort_order=9999,
                sub_categories=[],
                isDeleted=False,
                date_created=now,
                last_updated=now
            )
            uncat.save()

            # Add default 'None' subcategory
            uncat.add_subcategory(
                name=self.DEFAULT_SUBCATEGORY_NAME,
                description="Default holding subcategory for uncategorized products"
            )

            logger.info(f"Created default 'Uncategorized' category with ID: {sk}")
            self._send_category_notification(
                'created',
                'Uncategorized',
                sk,
                {'system_generated': True, 'action_type': 'system_initialization'}
            )

            return uncat.to_dict()
        except Exception as e:
            logger.error(f"Error ensuring uncategorized category exists: {e}")
            raise Exception(f"Error creating uncategorized category: {str(e)}")

    # -----------------------------------------------------------------
    # PRIVATE HELPERS (for DynamoDB implementation)
    # -----------------------------------------------------------------
    def _validate_category_data(self, category_data):
        """Validate category data (preserved from original)."""
        if not category_data:
            raise ValueError("Category data is required")
        category_name = category_data.get("category_name", "").strip()
        if not category_name:
            raise ValueError("Category name is required")
        existing = Category.get_by_name(category_name)
        if existing:
            raise ValueError(f"Category '{category_name}' already exists")
        status = category_data.get("status", "active")
        if status not in ['active', 'inactive']:
            raise ValueError("Status must be 'active' or 'inactive'")
        return category_name

    def _prepare_subcategories(self, existing_sub_categories):
        """Prepare subcategories with proper sequential IDs (legacy)."""
        # In DynamoDB, this is handled by model, but kept for compatibility
        from app.utils import generate_sk
        subs = []
        for i, sub in enumerate(existing_sub_categories):
            sub_id = generate_sk('SUB-', 'subcategory_seq')
            subs.append({
                'subcategory_id': sub_id,
                'name': sub.get('name', ''),
                'description': sub.get('description', ''),
                'sort_order': i,
                'status': 'active',
                'created_at': datetime.utcnow().isoformat(),
                'products': []
            })
        return subs

    def _get_next_subcategory_number(self):
        """Legacy – not used in DynamoDB."""
        from app.utils import generate_sk
        sk = generate_sk('SUB-', 'subcategory_seq')
        return int(sk.split('-')[1])

    def _add_product_counts_to_category(self, category):
        """Add product counts to category dict."""
        cat_dict = category.to_dict()
        cid = category.sk
        cat_dict['product_count'] = self._get_product_count_by_category(cid)
        for sub in cat_dict.get('sub_categories', []):
            sub['product_count'] = self._get_product_count_by_subcategory(cid, sub['name'])
        return cat_dict

    def _get_product_count_by_category(self, category_id):
        """Count products in a category."""
        try:
            count = 0
            for _ in Product.category_index.query(
                "products",
                Product.category_id == category_id,
                filter_condition=Product.isDeleted == False
            ):
                count += 1
            return count
        except Exception as e:
            logger.error(f"Error counting products for category {category_id}: {e}")
            return 0

    def _get_product_count_by_subcategory(self, category_id, subcategory_name):
        """Count products in a subcategory."""
        try:
            count = 0
            for p in Product.category_index.query(
                "products",
                Product.category_id == category_id,
                filter_condition=Product.isDeleted == False
            ):
                if p.subcategory_name == subcategory_name:
                    count += 1
            return count
        except Exception as e:
            logger.error(f"Error counting products for subcategory {subcategory_name}: {e}")
            return 0

    def _get_products_by_subcategory(self, category_id, subcategory_name, include_deleted=False):
        """Get products by category and subcategory."""
        products = []
        filter_cond = None if include_deleted else (Product.isDeleted == False)
        for p in Product.category_index.query(
            "products",
            Product.category_id == category_id,
            filter_condition=filter_cond
        ):
            if p.subcategory_name == subcategory_name:
                products.append(p)
        return products

    def _get_product_by_identifier(self, identifier):
        """Get product by ID, SKU, barcode, or name."""
        try:
            if validate_product_id(identifier):
                return Product.get_by_id(identifier)
            p = Product.get_by_sku(identifier)
            if p:
                return p
            p = Product.get_by_barcode(identifier)
            if p:
                return p
            results = Product.search_by_name(identifier, limit=1)
            return results[0] if results else None
        except Exception as e:
            logger.error(f"Error getting product by identifier {identifier}: {e}")
            return None

    def _update_product_category(self, product_id, category_id, subcategory_name, current_user=None):
        """Update product's category reference."""
        try:
            product = Product.get_by_id(product_id)
            if not product:
                return False
            product.update_product(
                category_id=category_id,
                subcategory_name=subcategory_name
            )
            if current_user:
                product.add_sync_log(
                    source="system",
                    status="success",
                    action="category_update",
                    details=[{
                        "field": "category",
                        "old_value": f"{product.category_id}/{product.subcategory_name}",
                        "new_value": f"{category_id}/{subcategory_name}",
                        "updated_by": current_user.get('username', 'system')
                    }]
                )
            return True
        except Exception as e:
            logger.error(f"Error updating product category: {e}")
            return False

    def _log_category_audit(self, action, user, category, old_values=None, new_values=None, details=None):
        """Log category audit event."""
        try:
            changes = None
            if old_values or new_values:
                changes = json.dumps({
                    "old_values": self._convert_to_serializable(old_values) or {},
                    "new_values": self._convert_to_serializable(new_values) or {},
                    "changed_fields": list(new_values.keys()) if new_values else []
                })
            self.audit_service._create_audit_log(
                event_type=f"category_{action}",
                user_data=user,
                target_data={
                    "type": "category",
                    "id": category.sk,
                    "name": category.category_name
                },
                old_values=old_values,
                new_values=new_values,
                metadata=details,
                changes=changes
            )
        except Exception as e:
            logger.error(f"Failed to log category audit: {e}")

    def _log_product_category_audit(self, action, user, category, product, details=None):
        """Log product-category relationship audit."""
        try:
            self.audit_service._create_audit_log(
                event_type=f"product_category_{action}",
                user_data=user,
                target_data={
                    "type": "product_category",
                    "id": f"{product.sk}_{category.sk}",
                    "name": f"{product.product_name} in {category.category_name}"
                },
                metadata={
                    "product_id": product.sk,
                    "product_name": product.product_name,
                    "category_id": category.sk,
                    "category_name": category.category_name,
                    **(details or {})
                }
            )
        except Exception as e:
            logger.error(f"Failed to log product-category audit: {e}")

    def _convert_to_serializable(self, obj):
        """Convert object to JSON serializable format."""
        if isinstance(obj, dict):
            return {k: self._convert_to_serializable(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [self._convert_to_serializable(i) for i in obj]
        if isinstance(obj, Decimal):
            return float(obj)
        if isinstance(obj, datetime):
            return obj.isoformat()
        return obj